/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9wp9zM0aHmp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <Card className="w-full max-w-md shadow-md">
      <CardContent className="grid gap-4 p-6">
        <div className="flex items-center justify-between">
          <div className="space-y-1">
            <p className="text-2xl font-bold">$49.99</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">June 23, 2023 at 3:45 PM</p>
          </div>
          <CircleCheckIcon className="h-8 w-8 text-green-500" />
        </div>
        <div>
          <p className="text-sm text-gray-500 dark:text-gray-400">Payment received for your monthly subscription.</p>
        </div>
      </CardContent>
    </Card>
  )
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}
